#!/usr/bin/bash

set -eu

export GRPC_GO_LOG_VERBOSITY_LEVEL=99
export GRPC_GO_LOG_SEVERITY_LEVEL=info

: ${NAMESPACE:=default}

internal_args="-port ${PORT:-443} -tls -ca-cert /run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
host="grpc-interop.${NAMESPACE}.svc"

function oc_exec {
    set -o xtrace
    oc exec "$@"
    set +o xtrace
}

echo "running interop test cases on internal service $host"

if [ $# -eq 0 ]; then
    oc_exec grpc-interop -c client-shell -- /workdir/grpc-client -host $host $internal_args
else
    for testcase in "$@"; do
	oc_exec grpc-interop -c client-shell -- /workdir/grpc-client -host $host $internal_args $testcase
    done
fi
